N_ITEMS_IN_AUTOCOMPLETE = 100

# Cell
DEFAULT_CELL_RADIUS = 9
DEFAULT_CELL_COLOR = "Pink"
DEFAULT_CELL_LINE_COLOR = "Black"

# Nickel strip
NICKEL_STRIP_COLOR = (0.5, 0.5, 0.5, 0.0)
NICKEL_STRIP_LINE_POINT_COLOR = (0.0, 0.0, 0.0, 0.0)

# Unit : mm
NICKEL_STRIP_WIDTH = 8.0
NICKEL_STRIP_HEIGHT = 0.15 

# Unit : g
NICKEL_STRIP_WEIGHT_PER_MM3 = 0.00857


# Note : For now, these are made up, to see if the system works
# Unit : g
BATTERY_HOLDER_WEIGHT = 0.5
T_CONNECTOR_WEIGHT = 1.2
XT_60_CONNECTOR_WEIGHT = 1.5

# Prices

NICKEL_STRIP_PRICE_PER_MM = 0.0035