N_ITEMS_IN_AUTOCOMPLETE = 100

# Cell
DEFAULT_CELL_RADIUS = 9
DEFAULT_CELL_COLOR = "Pink"
DEFAULT_CELL_LINE_COLOR = "Black"

# Nickel strip
NICKEL_STRIP_COLOR = (0.5, 0.5, 0.5, 0.0)
NICKEL_STRIP_LINE_POINT_COLOR = (0.0, 0.0, 0.0, 0.0)

# Unit : mm
NICKEL_STRIP_WIDTH = 8
NICKEL_STRIP_HEIGHT = 0.15 